server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: @profile.active@
---
spring:
  profiles: dev
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Hayaking/spring-cloud-heat.git
          search-paths: /config/src/main/resources/static

