server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
spring:
  application:
    name: heat-provider


