server:
  port: 7999
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
spring:
  application:
    name: security

feign:
  hystrix:
    enabled: true
